### ISSUE TITLE
Line error icon remains after correction

### ISSUE THREAD

**Issue by TommyTheBlackbird** [Crunch/Crunch-2#158]
When you have a misspelling error and try to crunch, the line is marked with the error icon, but after correcting the error and crunching again, the line error mark remains.

The mark only disappears when you delete the whole line.

_Windows 10 (x64) / Crunch 2.1.0_

![crunch2_lineerror_remains](https://cloud.githubusercontent.com/assets/14106278/12752433/d52ea7c2-c9c2-11e5-9e38-b1e1b3af4c14.gif)

**Comment by matthew-dean** [comment]
I couldn't reproduce this. It should clear all annotations in the current editing session.

**Comment by dongully** [comment]
I had same probrem in Adobe Air 17, but resolved by updating to 20.
https://get.adobe.com/air/

**Comment by dongully** [comment]
I met same probrem.

Windows 7 (x64) / Crunch 2.1.0 / Adobe Air 20

If a line number which contains error has not changed after resolving the problem, occur this problem.(in TommyTheBlackbird example, 163 to 163.)
But, changed(e.g. 163 to 164.), error mark will be refleshed, and not occur this problem.

**Comment by matthew-dean** [comment]
Can you re-verify that this is still happening in latest builds?

**Comment by dongully** [comment]
re-verifiy in Version 2.1.5, but still happened.

![crunch](https://cloud.githubusercontent.com/assets/16263922/13903128/a649d87e-eeb0-11e5-9a49-2e5531280bcd.gif)
