### ISSUE TITLE
The cursor has a problem, the location is displayed.

### ISSUE THREAD

**Issue by xubing6243** [Crunch/Crunch-2#39]
os: windows7
![86002397-156f-4e5d-b382-b1955e33836e](https://cloud.githubusercontent.com/assets/4361465/9513059/4f059a16-4cbd-11e5-8425-002305a60d1b.png)

**Comment by matthew-dean** [comment]
Is the cursor always in the wrong position for you, or under certain conditions (resizing, switching tabs, etc)? Do any of those actions correctly re-position the cursor?

**Comment by xubing6243** [comment]
I am not very clear, this problem is not often appear! I don't know what's causing it!

**Comment by Pantyboy** [comment]
My cursor has an "extra" space between the character and the cursor itself.

It took me several attempts to delete a character before I figured this one out.

**Comment by matthew-dean** [comment]
@Pantyboy Also on Windows? If so, what version?

**Comment by TommyTheBlackbird** [comment]
It happens to me in Windows 10 (64 bits).

**Comment by Pantyboy** [comment]
@matthew-dean I'm using Windows 10, 64 bit.

**Comment by matthew-dean** [comment]
This one will probably prove difficult. It's either an Ace (editor) bug or a bug in Chromium for Windows. The only way this would happen (I think) is if it measured character width and the browser engine returned an inaccurate width.

See if you can note any pattern, like resizing / switching / anything like that. I might be able to make a workaround if I know where it happens.

**Comment by matthew-dean** [comment]
@Pantyboy For you, is this a problem all the time?

**Comment by Pantyboy** [comment]
@matthew-dean The gap is only really visible at the end of the line so this is only when you notice the problem.

![crunch_cursor_gap](https://cloud.githubusercontent.com/assets/6214205/9750616/065f1d3a-5692-11e5-8a1f-967325fc1824.jpg)

**Comment by mbl-at** [comment]
![crunch2](https://cloud.githubusercontent.com/assets/8981484/9844709/8c187926-5a93-11e5-88f6-e42aac6e84aa.gif)

**Comment by iamdave210** [comment]
![screencap](https://cloud.githubusercontent.com/assets/4050256/10054711/222c13d0-61f8-11e5-9357-e7699641449e.png)

Screen cap of the cursor issue in beta 6. I had just typed the 'x' in the screenshot. If I were to backspace once from where the cursor is the 'x' would be deleted.

**Comment by matthew-dean** [comment]
This is technically an Ace issue, which I've raised with them, but I'll try to keep figuring out a workaround. I think rather than measuring the actual position of those characters, Ace attempts to math it out by measuring individual characters and some similar CSS to what's rendered in order to guess the cursor position. It appears those guesses are sometimes wrong under some unknown circumstances which seem to have been triggered in Crunch.

**Comment by matthew-dean** [comment]
Is this still an issue as of beta 8 for you in Windows?

**Comment by Pantyboy** [comment]
@matthew-dean From my perspective, this is fixed. Great job!

**Comment by sacerro** [comment]
No problem with beta 8 on Windows 10 x64

**Comment by TommyTheBlackbird** [comment]
I'm still having some cursor issues (beta8 Win10 x64). The problem seems to appear when the cursor is next to some mark characters like colon and semicolon.

![crunch2-beta8-win10x64-cursor](https://cloud.githubusercontent.com/assets/14106278/10579808/99848e08-767a-11e5-9528-4e62dcfc692e.gif)

**Comment by matthew-dean** [comment]
@TommyTheBlackbird Nuts. It's hard to guess where the failure point is. It might be some combination of how Ace is measuring lines + font + Chrome + Windows font rendering. Are all of you in the Facebook beta testing group? I might have to do some test builds with slightly different settings to see what fixes it for you.

**Comment by nightwing** [comment]
@TommyTheBlackbird could you try the editor at https://ace.c9.io/#nav=about?

**Comment by matthew-dean** [comment]
Ah, I can reproduce now in a Parallels virtual Win 10.

**Comment by matthew-dean** [comment]
Apparently Atom, which is pretty similar to NW.js as far as platform, has had lots of text-measuring issues, especially in regards to ```text-rendering: optimizeLegibility```, and fonts with ligatures like Hasklig, which Crunch is currently using. See: https://github.com/atom/atom/pull/8811.

In the short term, if Ace doesn't have a fix, I might try to sub in Source Code Pro (which Hasklig is based on), and turn off optimizeLegibility (or ```text-rendering: geometricPrecision``` which I also have tried).

**Comment by matthew-dean** [comment]
Welp. I could reproduce, and now I can't. Seems random.

**Comment by matthew-dean** [comment]
Okay, with some more testing, I could reproduce cursor positioning problems on both Mac & Windows, not just Windows. After toggling ```text-rendering``` settings on/off, I think the problem might, in fact, be Hasklig, which claims to be a monospace font, but ends up *not* being monospace in Chromium. Ace only works with monospace fonts, so this is probably the issue. I'll do some test builds with Source Code Pro & text-rendering settings turned off for the editor.

**Comment by matthew-dean** [comment]
The problem was not the font. What the problem is, I'm not exactly sure, but I think I have a working workaround.

**Comment by matthew-dean** [comment]
Fixed in beta 9.

**Comment by TommyTheBlackbird** [comment]
Fix confirmed here! Nice job!

**Comment by mbl-at** [comment]
beta9 on win7 home premium x64 - working fine :+1:

**Comment by matthew-dean** [comment]
*whew *

**Comment by SBRK** [comment]
I had the same problem, only on Mac. On words like "difficult" the f and i would get grouped. This was due to a global `font-feature-settings: liga` I had.

I added 
```
  font-feature-settings: "liga" 0;
  font-variant-ligatures: none;
```

To my Ace editor wrapper and voila
